apiVersion: apps/v1
kind: Deployment
metadata:
  name: hit-counter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hit-counter
  template:
    metadata:
      labels:
        app: hit-counter
    spec:
      containers:
      - name: hit-counter
        image: aimvector/api-redis-ha:1.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"